modLoader="javafml"
loaderVersion="[${fml},)"
license="Apache License 2.0"
issueTrackerURL="https://github.com/MelanX/ExtraDisks/issues"

[[mods]]
modId="extradisks"
version="${version}"
displayName="Extra Disks"
updateJSONURL="https://assets.melanx.de/updates/extra-disks.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/extra-disks/"
credits="Thanks for raoulvdberge and Refined Storage for being a fancy mod! Thanks to Reborn Storage for most of the textures as well!"
authors="MelanX"
description='''
This mod adds a few bigger storage disks and blocks for Refined Storage by raoulvdberge.
'''

[[dependencies.extradisks]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.extradisks]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.extradisks]]
    modId="refinedstorage"
    mandatory=true
    versionRange="[1.12.4,)"
    ordering="NONE"
    side="BOTH"
