modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod.license}"
issueTrackerURL = "${mod.issue_url}"

[[mods]]
modId = "${mod.modid}"
version = "${mod.version}"
displayName="Extra Disks"
displayURL = "${mod.source_url}"
updateJSONURL = "https://assets.melanx.de/updates/extra-disks.json"
authors = "MelanX"
description = """
Extra Disks adds bigger disks to Refined Storage
"""

[[dependencies.${ mod.modid }]]
   modId = "neoforge"
   type = "required"
   versionRange = "[${mod.neoforge},)"
   ordering = "NONE"
   side = "BOTH"

[[dependencies.${ mod.modid }]]
   modId = "minecraft"
   type = "required"
   versionRange = "[${mod.minecraft},)"
   ordering = "NONE"
   side = "BOTH"

[[dependencies.${ mod.modid }]]
   modId = "refinedstorage"
   type = "required"
   versionRange = "[2.0.0-milestone.4.11,)"
   ordering = "NONE"
   side = "BOTH"

[[dependencies.${ mod.modid }]]
   modId = "mekanism"
   type = "optional"
   versionRange = "[10.6,11-)"
   ordering = "NONE"
   side = "BOTH"

[[dependencies.${ mod.modid }]]
   modId = "refinedstorage_mekanism_integration"
   type = "optional"
   versionRange = "[0.1.0,)"
   ordering = "NONE"
   side = "BOTH"
